### PR TITLE
Fixed Named Routing

### PR DESCRIPTION
**Pull request by Devank-Sachdeva**
Issue https://github.com/hackslash-nitp/cura/issues/52
Added all the routing stuff to a new file RouteGenerator.dart to not make main.dart messy
also added a file called StringScreenArguments.dart which is used in sending Multiple arguments on pushNamed routes.

All the route names are specified in the class itself with a routename property (which makes changing them easier by changing routename at only one place)

Fixed conflicts with previous pull request opened by me

### CODE REVIEW

**Review by RitwikSingh28 — CHANGES_REQUESTED** [review]
Splendid work :sparkles: 

Just some small changes need to be done before we may merge
- In the lib/shared/services/firebase_authentication.dart, we would like you to resolve the errors by providing with the routeName, just a small fix.
- Moreover, I would like to ask you to move the RouteGenerator.dart and stringScreenArguments.dart into the lib/shared/services folder.

**Comment by Devank-Sachdeva** [comment]
Thank you for the opportunity 😇

**Comment by Devank-Sachdeva** [comment]
@RitwikSingh28 I just noticed the import file lines in main.dart, org_chats_menu.dart, user_chats_menu.dart were not refactored. 
Can u reopen this pull request or shall make a new one ?

**Comment by RitwikSingh28** [comment]
@Devank-Sachdeva 
Yes, I just noticed it now as well. I am reopening this PR, please kindly make the necessary changes.

**Comment by Devank-Sachdeva** [comment]
@RitwikSingh28 Added new PR https://github.com/hackslash-nitp/cura/pull/57 can u review it 😀

**Comment by RitwikSingh28** [comment]
Sure...

**Pull request merged**
